let data = {"name":"Sangue (35/67)",
"children":[{"name":"Hemograma Completo (2/17)",
"children":[{"name":"Serie Vermelha (7/7)",
"children":[{"id_valor":1,"name":"Contagem de Hemacias: 5.78 milhoes/mm3","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":2,"name":"Dosagem da Hemoglobina: 15.7 g/dL","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":3,"name":"Avaliacao do Hematocrito: 49.4%","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":4,"name":"Volume Globular Medio: 85.4 fL","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":5,"name":"Hemoglobina Globular Media: 27.1 pg","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":6,"name":"Concentracao da Hemoglobina Glob Media: 31.7 g/dL","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":7,"name":"Indice de Anisocitose (RDW): 14.2%","id_metodo":1,"metodo":"automatizado e microscopia optica"}]},
{"name":"Serie Branca - Leucograma (10/10)",
"children":[{"id_valor":8,"name":"Contagem de Leucocitos: 6.7 mil/mm3","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":9,"name":"Basofilos: 0%","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":10,"name":"Eosinofilos: 4%","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":11,"name":"Neutrofilos Mielocitos: 0%","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":12,"name":"Neutrofilos Metamielocitos: 0%","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":13,"name":"Bastoes: 1%","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":14,"name":"Segmentados: 54%","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":15,"name":"Linfocitos: 31%","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":16,"name":"Monocitos: 10%","id_metodo":1,"metodo":"automatizado e microscopia optica"},
{"id_valor":17,"name":"Contagem de Plaquetas: 307 mil/mm3","id_metodo":1,"metodo":"automatizado e microscopia optica"}]}]},
{"name":"Hemoglobina Glicada (2/2)",
"children":[{"id_valor":18,"name":"Hemoglobina Glicada (Hba1c): 5.2%","id_metodo":2,"metodo":"turbidimetria, national glycohemoglobin standardization program (ngsp)"},
{"id_valor":19,"name":"Glicemia Media Estimada: 103 mg/dL","id_metodo":3,"metodo":"calculo matematico, american diabetes association  (ada)"}]},
{"name":"Glicose (1/1)",
"children":[{"id_valor":20,"name":"Glicose: 84 mg/dL","id_metodo":4,"metodo":"enzimatico"}]},
{"name":"Ureia (1/1)",
"children":[{"id_valor":21,"name":"Ureia: 27 mg/dL","id_metodo":5,"metodo":"cinetico uv"}]},
{"name":"Creatinina (1/1)",
"children":[{"id_valor":22,"name":"Creatinina: 1 mg/dL","id_metodo":6,"metodo":"colorimetrico"}]},
{"name":"Ferro (1/1)",
"children":[{"id_valor":23,"name":"Ferro: 110 mcg/dL","id_metodo":6,"metodo":"colorimetrico"}]},
{"name":"Capacidade de Combinacao do Ferro (1/1)",
"children":[{"id_valor":24,"name":"Capacidade Total de Combinacao do Ferro: 315 mcg/dL","id_metodo":7,"metodo":"calculo"}]},
{"name":"Indice de Saturacao da Transferrina (1/1)",
"children":[{"id_valor":25,"name":"Indice de Saturacao da Transferrina: 34.9%","id_metodo":7,"metodo":"calculo"}]},
{"name":"Amilase (1/1)",
"children":[{"id_valor":26,"name":"Amilase: 56 U/L","id_metodo":8,"metodo":"enzimatico colorimetrico"}]},
{"name":"Lipase (1/1)",
"children":[{"id_valor":27,"name":"Lipase: 35 U/L","id_metodo":8,"metodo":"enzimatico colorimetrico"}]},
{"name":"Calcio (1/1)",
"children":[{"id_valor":28,"name":"Calcio: 8.7 mg/dL","id_metodo":6,"metodo":"colorimetrico"}]},
{"name":"Fosforo (1/1)",
"children":[{"id_valor":29,"name":"Fosforo Inorganico: 3.2 mg/dL","id_metodo":6,"metodo":"colorimetrico"}]},
{"name":"Sodio (1/1)",
"children":[{"id_valor":30,"name":"Sodio: 142 mEq/L","id_metodo":9,"metodo":"eletrodo seletivo"}]},
{"name":"Potassio (1/1)",
"children":[{"id_valor":31,"name":"Potassio: 4.4 mEq/L","id_metodo":9,"metodo":"eletrodo seletivo"}]},
{"name":"Magnesio (1/1)",
"children":[{"id_valor":32,"name":"Magnesio: 2.1 mg/dL","id_metodo":6,"metodo":"colorimetrico"}]},
{"name":"Desidrogenase Latica (1/1)",
"children":[{"id_valor":33,"name":"Desidrogenase Latica Total: 359 U/L","id_metodo":5,"metodo":"cinetico uv"}]},
{"name":"Hepatograma (8/8)",
"children":[{"id_valor":34,"name":"Proteinas Totais: 6.9 g/dL","id_metodo":6,"metodo":"colorimetrico"},
{"id_valor":35,"name":"Transaminase Piruvica (Alt): 21 U/L","id_metodo":5,"metodo":"cinetico uv"},
{"id_valor":36,"name":"Transaminase Oxalacetica (AST): 18 U/L","id_metodo":5,"metodo":"cinetico uv"},
{"id_valor":37,"name":"Fosfatase Alcalina: 59 U/L","id_metodo":8,"metodo":"enzimatico colorimetrico"},
{"id_valor":38,"name":"Gama Glutamil Transpeptidase: 31 U/L","id_metodo":8,"metodo":"enzimatico colorimetrico"},
{"id_valor":39,"name":"Bilirrubina Direta: 0.3 mg/dL","id_metodo":6,"metodo":"colorimetrico"},
{"id_valor":40,"name":"Bilirrubina Indireta: 0.8 mg/dL","id_metodo":6,"metodo":"colorimetrico"},
{"id_valor":41,"name":"Bilirrubina Total: 1.1 mg/dL","id_metodo":6,"metodo":"colorimetrico"}]},
{"name":"Perfil Lipidico (7/7)",
"children":[{"id_valor":42,"name":"Colesterol: 177 mg/dL","id_metodo":8,"metodo":"enzimatico colorimetrico"},
{"id_valor":43,"name":"Colesterol - HDL: 52 mg/dL","id_metodo":8,"metodo":"enzimatico colorimetrico"},
{"id_valor":44,"name":"Triglicerideos: 123 mg/dL","id_metodo":8,"metodo":"enzimatico colorimetrico"},
{"id_valor":45,"name":"Colesterol - LDL: 100 mg/dL","id_metodo":8,"metodo":"enzimatico colorimetrico"},
{"id_valor":46,"name":"Colesterol - VLDL: 25 mg/dL","id_metodo":8,"metodo":"enzimatico colorimetrico"},
{"id_valor":47,"name":"Colesterol - Nao HDL: 125 mg/dL","id_metodo":8,"metodo":"enzimatico colorimetrico"},
{"id_valor":48,"name":"Aspecto do Soro:limpido","id_metodo":8,"metodo":"enzimatico colorimetrico"}]},
{"name":"Creatino Quinase (1/1)",
"children":[{"id_valor":49,"name":"Creatino Quinase Total: 84 U/L","id_metodo":5,"metodo":"cinetico uv"}]},
{"name":"Albumina (1/1)",
"children":[{"id_valor":50,"name":"Albumina: 4.6 g/dL","id_metodo":6,"metodo":"colorimetrico"}]},
{"name":"T4 Livre (1/1)",
"children":[{"id_valor":51,"name":"Tiroxina Livre: 1.7 ng/dL","id_metodo":10,"metodo":"eletroquimioluminescencia"}]},
{"name":"TSH (1/1)",
"children":[{"id_valor":52,"name":"Hormonio Estimulante da Tireoide: 0.32 mcUI/mL","id_metodo":10,"metodo":"eletroquimioluminescencia"}]},
{"name":"Homa-Beta (1/1)",
"children":[{"id_valor":53,"name":"Homa-Beta (Homeostatic Model Assessment): 191 ","id_metodo":7,"metodo":"calculo"}]},
{"name":"Homa-Ir (1/1)",
"children":[{"id_valor":54,"name":"Homa-Ir (Homeostatic Model Assessment): 2.3 ","id_metodo":7,"metodo":"calculo"}]},
{"name":"Insulina (1/1)",
"children":[{"id_valor":55,"name":"Insulina: 11.1 mcU/mL","id_metodo":10,"metodo":"eletroquimioluminescencia"}]},
{"name":"Anti-Tireoglobulina (1/1)",
"children":[{"id_valor":56,"name":"Pesq. de Anticorpos Anti-Tireoglobulina: 10 U/mL","id_metodo":10,"metodo":"eletroquimioluminescencia"}]},
{"name":"TPO - Antiperoxidase Tiroideana (1/1)",
"children":[{"id_valor":57,"name":"Anticorpo Antiperoxidase Tiroideana: 7.8 U/mL","id_metodo":10,"metodo":"eletroquimioluminescencia"}]},
{"name":"Proteina C Reativa Ultra-Sensivel (1/1)",
"children":[{"id_valor":58,"name":"Proteina C Reativa Ultra-Sensivel: 0.08 mg/dL","id_metodo":11,"metodo":"imunoturbidimetrico"}]},
{"name":"Vitamina B12 (1/1)",
"children":[{"id_valor":59,"name":"Dosagem de Vitamina B12 (Cobalamina): 238 pg/mL","id_metodo":12,"metodo":"ensaio imunoenzimatico"}]},
{"name":"Acido Folico (1/1)",
"children":[{"id_valor":60,"name":"Acido Folico: 8.44 ng/mL","id_metodo":12,"metodo":"ensaio imunoenzimatico"}]},
{"name":"Ferritina (1/1)",
"children":[{"id_valor":61,"name":"Ferritina: 59.9 ng/mL","id_metodo":12,"metodo":"ensaio imunoenzimatico"}]},
{"name":"Vitamina D, 25-Hidroxi (1/1)",
"children":[{"id_valor":62,"name":"25-Hidroxi Vitamina D: 25.1 ng/mL","id_metodo":13,"metodo":"imunoensaio por quimioluminescencia"}]},
{"name":"PTH - Paratormonio (Molecula Inteira) (1/1)",
"children":[{"id_valor":63,"name":"Paratormonio (Molecula Inteira): 41.5 pg/mL","id_metodo":14,"metodo":"ensaio imunoenzimatico por quimioluminescencia"}]},
{"name":"PSA Total E Livre (3/3)",
"children":[{"id_valor":64,"name":"Antigeno Prostatico Especifico Total: 2.65 ng/mL","id_metodo":14,"metodo":"ensaio imunoenzimatico por quimioluminescencia"},
{"id_valor":65,"name":"Ag. Prostatico Especifico, Fracao Livre: 0.62 ng/mL","id_metodo":14,"metodo":"ensaio imunoenzimatico por quimioluminescencia"},
{"id_valor":66,"name":"Relacao PSA Livre/PSA Total: 0.23 ","id_metodo":14,"metodo":"ensaio imunoenzimatico por quimioluminescencia"}]},
{"name":"Tireoglobulina (1/1)",
"children":[{"id_valor":67,"name":"Tireoglobulina: 0.1 ng/mL","id_metodo":15,"metodo":"quimioluminescencia"}]}]};